Algoritmo "Combinações"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2021
Var
   C1, C2 : Inteiro


Inicio
      Para C1 <- 1 ate 3 faça
           Para C2 <- 1 ate 3 faça
                EscrevaL (C1, C2)
           FimPara
      FimPara

Fimalgoritmo