Algoritmo "PARA somador de valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2021
Var
   C, S, V : Inteiro


Inicio
      Para C <- 1 ate 5 passo 1 faca
           EscrevaL ("Digite um valor: ")
           Leia (V)
           S <- S + V
      FimPara
      Escreva ("A soma dos valores é: ", S)

Fimalgoritmo