Algoritmo "ParouImpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2021
Var
   N: Inteiro

Inicio
   EscrevaL ("Digite um número: ")
   Leia (N)
   Se (N % 2 = 0) entao
      EscrevaL ("O n° ", N," é par.")
   senao
      EscrevaL ("O n° ", N," é ímpar.")
   FimSe

Fimalgoritmo